import 'package:flutter/material.dart';
import 'package:flutter_notas/app/shared/models/theme_model.dart';

const themes = [
  ThemeModel(
    title: 'Padrão',
    fontColor: null,
    bgColor: null,
    hintColor: null,
    lastModifyColor: null,
    bgAsset: null,
  ),
  ThemeModel(
    title: 'Slate Blue 1',
    fontColor: null,
    bgColor: Color.fromARGB(255, 131, 111, 255),
    hintColor: null,
    lastModifyColor: null,
    bgAsset: null,
  ),
  ThemeModel(
    title: 'Royal Blue',
    fontColor: null,
    bgColor: Color.fromARGB(255, 65, 105, 225),
    hintColor: null,
    lastModifyColor: null,
    bgAsset: null,
  ),
  ThemeModel(
    title: 'Medium Turquoise',
    fontColor: null,
    bgColor: Color.fromARGB(255, 72, 209, 204),
    hintColor: null,
    lastModifyColor: null,
    bgAsset: null,
  ),
  ThemeModel(
    title: 'Light Sea Green',
    fontColor: null,
    bgColor: Color.fromARGB(255, 32, 178, 170),
    hintColor: null,
    lastModifyColor: null,
    bgAsset: null,
  ),
  ThemeModel(
    title: 'Dark Slate Gray',
    fontColor: null,
    bgColor: Color.fromARGB(255, 47, 79, 79),
    hintColor: null,
    lastModifyColor: null,
    bgAsset: null,
  ),
  ThemeModel(
    title: 'Dark Slate Blue',
    fontColor: null,
    bgColor: Color.fromARGB(255, 72, 61, 139),
    hintColor: null,
    lastModifyColor: null,
    bgAsset: null,
  ),
  ThemeModel(
    title: 'Imagem',
    fontColor: Colors.white,
    bgColor: null,
    hintColor: Color.fromARGB(125, 255, 255, 255),
    lastModifyColor: Color.fromARGB(200, 255, 255, 255),
    bgAsset: 'assets/images/backgrounds/bg_01.jpg',
  ),
  ThemeModel(
    title: 'Imagem',
    fontColor: Colors.black,
    bgColor: Color.fromARGB(255, 0, 0, 0),
    hintColor: Color.fromARGB(125, 0, 0, 0),
    lastModifyColor: Color.fromARGB(200, 0, 0, 0),
    bgAsset: 'assets/images/backgrounds/bg_02.jpg',
  ),
  ThemeModel(
    title: 'Imagem',
    fontColor: Colors.black,
    bgColor: Color.fromARGB(255, 0, 0, 0),
    hintColor: Color.fromARGB(125, 0, 0, 0),
    lastModifyColor: Color.fromARGB(200, 0, 0, 0),
    bgAsset: 'assets/images/backgrounds/bg_03.jpg',
  ),
  ThemeModel(
    title: 'Imagem',
    fontColor: Colors.black,
    bgColor: Color.fromARGB(255, 0, 0, 0),
    hintColor: Color.fromARGB(125, 0, 0, 0),
    lastModifyColor: Color.fromARGB(200, 0, 0, 0),
    bgAsset: 'assets/images/backgrounds/bg_04.jpg',
  ),
  ThemeModel(
    title: 'Imagem',
    fontColor: Colors.black,
    bgColor: Color.fromARGB(255, 0, 0, 0),
    hintColor: Color.fromARGB(125, 0, 0, 0),
    lastModifyColor: Color.fromARGB(200, 0, 0, 0),
    bgAsset: 'assets/images/backgrounds/bg_05.jpg',
  ),
  ThemeModel(
    title: 'Imagem',
    fontColor: Colors.black,
    bgColor: Color.fromARGB(255, 0, 0, 0),
    hintColor: Color.fromARGB(125, 0, 0, 0),
    lastModifyColor: Color.fromARGB(200, 0, 0, 0),
    bgAsset: 'assets/images/backgrounds/bg_06.jpg',
  ),
];
